######################################################################
# GitLab CI build script for the Symbiotic project                   #
######################################################################
image: registry.gitlab.com/kpmeen/docker-scala-sbt:scala_2.12

variables:
  CI: "true"
  DOCKER_DRIVER: overlay
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"
  # Envs for executing tests
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SYMBIOTIC_MONGO_HOST: "symbiotic-mongo"
  SYMBIOTIC_MONGO_PORT: 27017
  SYMBIOTIC_POSTGRES_HOST: "postgres"
  SYMBIOTIC_ELASTICSEARCH_HOST: "elasticsearch"

cache:
  untracked: true
  paths:
    - cache

stages:
  - stylecheck
  - test
  - publishDocker
  - release

check style and formatting:
  stage: stylecheck
  tags:
    - docker
  script:
    # Ensure that the pipeline fails fast if there are issues with the
    # style or formatting
    - sbt clean scalastyle scalafmt
    - git diff --exit-code || (echo "ERROR Code formatting check failed, see differences above."; false)

run test suites:
  stage: test
  tags:
    - docker
  services:
    - name: mongo:latest
      alias: symbiotic-mongo
      command: ["mongod", "--quiet", "--smallfiles", "--storageEngine", "wiredTiger"]
    - name: registry.gitlab.com/kpmeen/docker-postgres-test:latest
      alias: postgres
    - name: kpmeen/docker-elasticsearch:latest
      alias: elasticsearch
  coverage: '/\[info]\sAll\sdone\.\sCoverage\swas\s\[(.*)%\]/'
  script:
    - sbt coverage test coverageReport
    - sbt coverageAggregate codacyCoverage

publish docker containers:
  stage: publishDocker
  tags:
  - docker
  services:
    - docker:dind
  script:
    - sbt docker:publish
  only:
    - master@kpmeen/symbiotic
