######################################################################
# GitLab CI build script for the Symbiotic project                   #
######################################################################
image: kpmeen/docker-symbiotic-build

variables:
  DOCKER_DRIVER: overlay
  # Setting specific folder for sbt-coursier to cache artifacts
  COURSIER_CACHE: "/root/cache/coursier"

cache:
  untracked: true
  paths:
    - cache

stages:
  - stylecheck
  - test

check style and formatting:
  stage: stylecheck
  script:
    # Ensure that the pipeline fails fast if there are issues with the
    # style or formatting
    - sbt clean scalastyle scalafmt
    - git diff --exit-code || (echo "ERROR Code formatting check failed, see differences above."; false)

run test suites:
  stage: test

  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    SYMBIOTIC_MONGO_HOST: "symbiotic-mongo"
    SYMBIOTIC_MONGO_PORT: 27017
    SYMBIOTIC_POSTGRES_HOST: "postgres"
    SYMBIOTIC_ELASTICSEARCH_HOST: "elasticsearch"

  services:
    - name: mongo:latest
      alias: symbiotic-mongo
      command: ["mongod", "--quiet", "--smallfiles", "--replSet", "symbiotic-ci", "--storageEngine", "wiredTiger"]
    - name: postgres:latest
    - name: kpmeen/docker-elasticsearch:latest
      alias: elasticsearch

  script:
    # Initialize the mongodb replica set
    - mongo --host symbiotic-mongo --eval "printjson(rs.initiate())"
    # Execute CI script
    - sbt coverage test coverageReport
    - ./gitlab-ci.sh

