######################################################################
# GitLab CI build script for the MUSIT backend project               #
######################################################################
image: kpmeen/docker-symbiotic-build

test:
  script:
    # Start the MongoDB server as a replica set
    - if [ -d "dbfiles" ]; then rm -rf dbfiles; fi; mkdir dbfiles;
    - mongod --smallfiles --replSet symbiotic-ci --storageEngine wiredTiger --dbpath dbfiles &
    - sleep 10s
    - mongo --eval "printjson(rs.initiate())"
    # Execute CI script
    - ./gitlab-ci.sh
    # Check if the scalariform modified any files during the build. If yes, fail the build.
    - git diff --exit-code || (echo "ERROR Scalariform check failed, see differences above."; false)

