######################################################################
# GitLab CI build script for the Symbiotic project                   #
######################################################################
image: kpmeen/docker-symbiotic-build

variables:
  DOCKER_DRIVER: overlay

services:
  - mongo:latest
  - postgres:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  SYMBIOTIC_POSTGRES_HOST: postgres

stages:
  - test

test:
  stage: test
  script:
    # Start the MongoDB server as a replica set
    - if [ -d "dbfiles" ]; then rm -rf dbfiles; fi; mkdir dbfiles;
    - mongod --smallfiles --replSet symbiotic-ci --storageEngine wiredTiger --dbpath dbfiles &
    - sleep 10s
    - mongo --eval "printjson(rs.initiate())"
    # Check if the scalafmt modified any files during the build. If yes, fail the build.
    - sbt clean scalastyle scalafmt
    - git diff --exit-code || (echo "ERROR Code formatting check failed, see differences above."; false)
    # Execute CI script
    - sbt coverage test coverageReport
    - ./gitlab-ci.sh

